trigger:
- pull_request

pool:
  vmImage: 'ubuntu-latest'

variables:
  POSTGRES_DB: $(POSTGRES_DB)
  POSTGRES_USER: $(POSTGRES_USER)
  POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
  POSTGRES_HOST: 'localhost'
  POSTGRES_PORT: '5432'

steps:
- checkout: self

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
    addToPath: true

- script: |
    curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    export DOCKER_HOST=unix:///var/run/docker.sock
    composer install
    sail up -d
    # Wait for the database to start
    sleep 15
  displayName: 'Install dependencies and start Sail'

- script: |
    export DOCKER_HOST=unix:///var/run/docker.sock
    sail test
  displayName: 'Run tests'
