name: Laravel Sail CI

on:
  push:
    branches: [develop, master]
    pull_request:
      branches: *

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-cli-action@v1
        with:
          compose-version: '2.0.0'

      - name: Start Laravel Sail
        run: |
          export DOCKER_HOST=unix://$RUNNER_WORKSPACE/docker.sock
          sail up -d

      - name: Install dependencies
        run: |
          export DOCKER_HOST=unix://$RUNNER_WORKSPACE/docker.sock
          sail composer install --optimize-autoloader --no-interaction

      - name: Run tests
        run: |
          export DOCKER_HOST=unix://$RUNNER_WORKSPACE/docker.sock
          sail test
